[project]
name = "django_5p2_tutorial"
version = "0.0.0"
description = "tutorial for django 5.2 and uv"
readme = ""
requires-python = ">=3.12,<3.13"
dependencies = [
    "Django~=5.2.0",
]

[dependency-groups]
local = []
staging = []
prod = []
